# Generated by Django 4.2.20 on 2025-05-12 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleimage', models.ImageField(upload_to='vehicleimg')),
                ('modelname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('appointmentdate', models.DateField(null=True)),
                ('slot', models.CharField(choices=[('A', 'Afternoon'), ('E', 'Evening'), ('M', 'Morning')], default='A', max_length=2)),
                ('location', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
