# Generated by Django 4.2.20 on 2025-05-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
