# Generated by Django 4.2.20 on 2025-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productcategory',
            field=models.CharField(choices=[('1', 'Electric Buses'), ('2,', 'Charging Equipment'), ('3', 'Spare Parts'), ('4', 'Accessories')], default='1', max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='productimg',
            field=models.ImageField(default=1, upload_to='productimg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
