# Generated by Django 4.2.20 on 2025-04-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserModelApp', '0004_rename_phone_number_customuser_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
