# Generated by Django 4.2.20 on 2025-04-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserModelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fullname',
        ),
    ]
