# Generated by Django 4.2.20 on 2025-04-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserModelApp', '0003_rename_phonenumber_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
